AllCops:
  Exclude:
    - vendor/**/*

Style/Encoding:
  Enabled: false
Style/GlobalVars:
  Enabled: false
LineLength:
  Max: 200
MethodLength:
  Max: 30
Metrics/AbcSize:
  Enabled: false
FileName:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
ParenthesesAsGroupedExpression:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
EndOfLine:
  Enabled: false
